プロジェクト名変更アイコンの追加、変更処理実装
violet-ts/violet pull request #102
Opened 2021-11-14 13:41 UTC by shuheiest

### 対応内容
 - プロジェクト名の右に変更アイコンを追加しました。
 - アイコン押下後にプロジェクト名を変更する処理を実装しました。
    変更時にアイコン名も修正

### 動作
![動作確認](https://user-images.githubusercontent.com/88891567/141683627-ce566e0a-81a1-4ed2-a07c-a2e82324e630.gif)

2021-11-14 18:59 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    if (!updateProject?.body) return
updateProjectがないのはわかるがbodyがないことはあるの？

2021-11-14 18:59 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +              tabs: d.tabs,
{...d, name: updateProject.body.name }

2021-11-14 19:00 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    ][0]
配列に入れてゼロ取り出すの無意味

2021-11-14 19:01 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +  justify-content: center;
text-align: centerだけで良さそう

2021-11-14 19:01 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/Explorer/index.tsx
> +          ></UpdateProjectName>
/>

2021-11-14 19:03 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +      {isUpdating && <Loading />}
Loading一瞬たりとも表示されないのでは？

2021-11-15 03:01 UTC, solufa requested changes
status変えてなかった

2021-11-15 04:33 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +      {isUpdating && <Loading />}
一瞬たりとも表示されなかったので、削除しました。

2021-11-15 04:33 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/Explorer/index.tsx
> +          ></UpdateProjectName>
修正しました。

2021-11-15 04:34 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +  justify-content: center;
text-align: centerのみでレイアウト崩れなど起きなかったので、修正しました。

2021-11-15 04:34 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    ][0]
修正しました。

2021-11-15 04:35 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +              tabs: d.tabs,
修正しました。

2021-11-15 04:36 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    if (!updateProject?.body) return
使用したい値がbodyだったので上記のように記載していましたが、
ご指摘の通りupdateProjectがあることさえ確認していれば問題ないため修正しました。

2021-11-15 04:44 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    updateProcess(label)
「Process」は意図的な名前？

2021-11-15 04:45 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    props.confirmName()
非同期なupdateProcessが完了する前にconfirmNameを呼ぶけどOK？
ローディング消すのではなく、非同期処理している間ちゃんと表示されるようにして

2021-11-15 12:03 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    props.confirmName()
updateProcessが完了してからconfirmNameを呼びたいため、処理を修正しました。
ご指摘ありがとうございます。

2021-11-15 12:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    const updateProject = await api.browser.projects
APIの返り値が命令形なのは不自然
これだと関数名っぽい

名詞Processが突然現れて意味不明

2021-11-15 14:43 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/UpdateProjectName.tsx
> +    const updateProject = await api.browser.projects
APIの返り値はアップデートされたプロジェクトデータになるので、
その点も踏まえて修正しました。
またプロジェクトネームをアップデートする関数名にprocessが入っていたため、そちらも修正しました。
関数名などについては今後以下を参考にしながら付けていきたいと思います。
 - [うまくメソッド名を付けるための参考情報](https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6)
 - [codic](https://codic.jp/engine)

2021-11-16 14:12 UTC, solufa approved these changes
LGTM

2021-11-16 14:12 UTC, merged