アイコン変更のUI作成とアイコン変更処理の実装
violet-ts/violet pull request #139
Opened 2021-11-28 14:09 UTC by shuheiest

### 内容
 - プロジェクト名の変更処理とアイコン変更を１つのモーダルにまとめました。
 - 新規にアイコン変更処理を実装しました。
 
### 動
![動作確認](https://user-images.githubusercontent.com/88891567/143771331-2f26efac-263e-4339-bd38-9f04c40f1c1d.gif)

2021-11-28 15:34 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectConfig.tsx
> +    const iconExt = iconImageFile?.name.substring(iconImageFile.name.indexOf('.') + 1)
```suggestion
    const iconExt = iconImageFile?.name.substring(iconImageFile.name.lastIndexOf('.') + 1)
```

とりあえず形的には

2021-11-28 15:39 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectNameUpdate.tsx
> +    [props]
```suggestion
    [props.setNewProjectName]
```

基本的に最小限に依存させたほうがいいと思う (`api` はあれ一個で不変なのでいいと思う)

2021-11-28 15:42 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectNameUpdate.tsx
> +      setLabel(e.target.value), props.setNewProjectName(e.target.value)
comma operator 使わずに

2021-11-28 15:43 UTC, LumaKernel commented
形式的な行単位のレビューは書いているけど、もう少しアプローチを変えたほうが良さそう。

2021-11-29 02:16 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectNameUpdate.tsx
> +  confirmName: () => void
rename this as `on...`

2021-11-29 02:16 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectNameUpdate.tsx
> +  confirmName: () => void
on... 系は optional

2021-11-29 02:16 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectConfig.tsx
> +export const ProjectConfig = (props: { onComplete: () => void; project: BrowserProject }) => {
on 系は optional

2021-11-29 02:16 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectConfig.tsx
> +  }, [])
とりあえずここは見た目がありえない。 感覚的にそうだと感じるというのを伝えたい。

unmount 後の再描画ないし。メモリリーク回避でもこの形になることはなさそう。

2021-12-01 16:43 UTC, shuheiest commented
レビューありがとうございます。
指摘いただいた箇所については修正しました。
https://github.com/violet-ts/violet/pull/139#discussion_r757997523
上記はメモリリーク回避のために処理してみましたが、もう一度修正してみます。
メモリリーク回避の対応については以下で対応します。
#138

2021-12-01 19:27 UTC, LumaKernel commented
@shuheiest 
いや、その issue には memory leak という文言こそあるが、上記レビューは「 useEffect がメモリリークがある状態からない状態にすることはないはず」と言っている。そのエラーが出たからと言って必ずメモリリークしているとは限らない。
例えば setInterval を適切に clearInterval していない場合などがメモリリークが起きるケースで、件の issue が言っているのもそういったケース。

2021-12-11 12:56 UTC, shuheiest commented
@LumaKernel 
上記、理解しました。
ありがとうございます。

2021-12-13 12:43 UTC, LumaKernel commented
/deploy

2021-12-14 07:05 UTC, solufa commented on pkg/api/api/browser/projects/_projectId@string/index.ts
> +    reqBody: { name: string; iconName?: string | null; imageFile?: Blob }
iconNameって undefined | string | null の3分岐も必要？

2021-12-14 07:06 UTC, solufa commented on pkg/api/api/browser/projects/_projectId@string/controller.ts
> +      })
PUT処理全部をupdateProjectIconにまとめてコントローラーにロジックを書かないようにする

2021-12-15 03:45 UTC, solufa commented on pkg/def/constants/index.ts
> +    type: 'image/',
これ合ってる？

2021-12-15 03:45 UTC, solufa commented on pkg/lib/types/api.d.ts
> +  iconUrl?: string | null
これも3分岐にする意図がわからない

2021-12-15 11:32 UTC, solufa commented on pkg/api/src/service/browser.ts
> +        ? (`${dotenv.S3_ENDPOINT}/${bucketOriginal}/icon/${p.projectId}/${p.iconName}` as ProjectIconPath)
ProjectIconPathを返す関数を定義する

2021-12-15 11:39 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/IconUpload.tsx
> +  const [iconImageUrl, setIconImageUrl] = useState('')
iconImageFileを親からもらえばここで状態管理しなくてよいのでは

2021-12-15 11:41 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/IconUpload.tsx
> +    reader.readAsDataURL(imageFile)
FileReaderじゃなくURL.createObjectURLで作るのがよい
revokeし忘れないように注意

2021-12-15 11:42 UTC, solufa requested changes
レビュー遅れました、修正お願いします

2021-12-24 11:18 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectBar.tsx
> +  }
```ts
const getIconImageUrl = (projectId: ProjectId) => projects.find((d) => d.id === projectId)?.iconUrl
```
だけで返り値が `string | undefined` にならないか？

2021-12-24 11:19 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/ProjectConfig.tsx
> +    setIconImageFile(imageFile)
await ないけど async ?

2021-12-24 11:30 UTC, solufa approved these changes
LGTM

2021-12-24 11:33 UTC, merged