ワークページング
violet-ts/violet pull request #140
Opened 2021-11-28 16:07 UTC by maihrs55

## Overview
- 上下ボタンをクリックすると隣接のリビジョンに移動する
    - Resolves #111 
- 上下ボタンの下部にリビジョン追加ボタンを設置

## 画面イメージ
![paging](https://user-images.githubusercontent.com/52160187/143776074-bad9a0bd-dfaf-40a1-ac1a-eaabac38051c.gif)

## ToDo
- IDを取るためにリビジョンごとに上下ボタンを設置しているので左側に固定する
    - #88 で対応予定

2021-11-28 16:15 UTC, maihrs55 commented
/build/api
/build/web
/build/lambda/conv2img

2021-11-28 16:21 UTC, maihrs55 commented
preview/start

2021-11-28 16:33 UTC, LumaKernel commented
/help

2021-11-28 16:35 UTC, LumaKernel commented
/build/lambda/apiexec

/preview/start

/prisma/db/seed

`/deploy` 一発でいける。bucket をパブリックにするのをまだしていないのでそれに依存しているとそこはまだ動かない…

2021-11-28 16:54 UTC, LumaKernel commented
今作業してる。
でも多分どちらにせよ PutBucket 時に public になるように設定する必要があるかも。
minio は オブジェクト単位の ACL はないけど S3 にはある。

2021-11-28 16:59 UTC, LumaKernel commented
/preview/start

これでリソースベースポリシーとCORSは問題ないと思う。
オブジェクト単位ACLはどうなるか見てみよう。

2021-11-28 17:05 UTC, LumaKernel commented
/prisma/migrate/deploy

/prisma/db/seed

マイグレーション抜けてた

2021-11-28 17:14 UTC, LumaKernel commented
うん、だめですね。putObject 時に指定が必要。コード内の必要な `putObject` に `ACL: 'public-read'` を追加してください。
original も普通に誰でも download できるようにすると思うので public read でいいのではないかな？

2021-11-28 17:39 UTC, LumaKernel commented
あと `` S3_ENDPOINT ?? `https://${bucket}.s3.amazonaws.com` `` とかしないといけないな

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/Revision/AlertModal.tsx
> +  useEffect(() => setOpenAlert(props.isOpen), [props.isOpen])
useState いる？もしくは useMemo かそのまま const

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/components/atoms/Scroller.tsx
> +export const Scroller = (id: string) =>
これは component でもなんでもないし lowerCamelCase かと思います

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +        <MainContent key={i} data-search-id={revision.id}>
全体的に言えることですが `key` は基本 index を使わないように考えてみてください。たとえばここは `revision` の id とか。再描画が増える、かどうかは厳密にはわかりかねますが、アニメーションなどを考えると、同じものが同じ ReactNode であるようにしたい。例えばですけど、[a,b,c] が [b,c,d] に変わるとき、

- a -> b
- b -> c
- c -> d

vs

- a (消える)
- b (キープ)
- c (キープ)
- d (増える)

上のようになるのが今のindexをkeyに使う書き方。


[Reactのkey propに配列のindexを使うことが良くない理由](https://zenn.dev/luvmini511/articles/f7b22d93e9c182) などのような記事もある
( 私も読んでないので読んでみます )

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/Revision/AlertModal.tsx
> +export const AlertModal = (props: { isOpen: boolean }) => {
`isOpen` は `open` に統一しませんか？という提案

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/Revision/index.tsx
> +      ? void props.sendFormData(file)
ここだけじゃないですが、副作用を三項演算子でさばくのは、 `if (cond) expr;` を `cond && expr;` とかくぐらいなんかモヤっとする書き方だと感じるので TSX 内以外では使わないほうがいいんじゃないかと思っていますがどう思いますか

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    fileTypes.some((f) => file.type === f.type) ? void sendFormData(file) : setOpenModal(true)
三項演算子、他の箇所のレビューと同様

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/PaginationBar.tsx
> +export const PaginationBar = (props: { clickchevron: (chevronup: boolean) => boolean }) => {
```suggestion
export const PaginationBar = (props: { clickChevron: (chevronup: boolean) => boolean }) => {
```

2021-11-29 01:33 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/PaginationBar.tsx
> +const ChevronUP = styled.div`
```suggestion
const ChevronUp = styled.div`
```

2021-11-30 13:42 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +        <MainContent key={i} data-search-id={revision.id}>
そこまで考えられていなかったです。記事読んでみます。
ひとまず今回の実装分を修正します。

2021-11-30 21:17 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/PaginationBar.tsx
> +export const PaginationBar = (props: { clickchevron: (chevronup: boolean) => boolean }) => {
修正しました。

2021-11-30 21:17 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/PaginationBar.tsx
> +const ChevronUP = styled.div`
修正しました。

2021-11-30 21:28 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Revision/AlertModal.tsx
> +export const AlertModal = (props: { isOpen: boolean }) => {
openに統一すること、賛成です。修正しました。

2021-11-30 21:40 UTC, maihrs55 commented on pkg/web/src/components/atoms/Scroller.tsx
> +export const Scroller = (id: string) =>
修正しました。

2021-11-30 21:44 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Revision/AlertModal.tsx
> +  useEffect(() => setOpenAlert(props.isOpen), [props.isOpen])
useStateを使わない方針で修正しました。

2021-12-01 14:02 UTC, maihrs55 commented
@LumaKernel 

> あと `` S3_ENDPOINT ?? `https://${bucket}.s3.amazonaws.com` `` とかしないといけないな

これはうまくできていれば、このPRでビルドした環境でもファイルがアップロードされて、
画面に表示されるはず...ということであっていますか？

2021-12-01 17:00 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    fileTypes.some((f) => file.type === f.type) ? void sendFormData(file) : setOpenModal(true)
上に同じく修正しました。

2021-12-01 19:20 UTC, LumaKernel commented
@maihrs55 
そう。いまは URL が undefined://... になる。
`atoms/Scroller` は場所を移そう。React component ではない。
あと putObject はもう1箇所あったはず。 VSCode や GitHub Codespace の検索機能、これらの GoToReference 機能、grep や rg みたいなツールをつかって探してみて下さい。

2021-12-02 13:14 UTC, maihrs55 commented
/preview/start

2021-12-02 13:24 UTC, LumaKernel commented
リビルドが必要なので更新したら基本 `/deploy` をしておくと確実です！
CI は GitHub Actions の Ubuntu 環境に更新がありそう。後で見ておきます。

/deploy

2021-12-02 13:47 UTC, LumaKernel commented
`https://vio-e-949029-d-s-conv-20211128164148410800000004.s3.amazonaws.com/vio-e-949029-d-s-conv-20211128164148410800000004/works/converted/projects/82116895-a386-8a33-f6e0-347408413e33/revisions/089f55be-c106-424a-bddc-afcd24528f60/info.json`
`https://vio-e-949029-d-s-conv-20211128164148410800000004.s3.amazonaws.com/works/converted/projects/f1ba8e31-1f45-bc16-fb72-c10355cae08b/revisions/95bf4fa1-daa3-4560-be88-9baebc21ca4f/info.json`

上が実際投げているもの。minio との差異吸収をお願いします。`<bucket>.s3.amazonaws.com/<key>` vs `<minio-endpoint>/<bucket>/<key>`

2021-12-02 22:45 UTC, maihrs55 commented
- テストデータとして保存されているデータは表示されました。
https://vio-e-949029-d-s-conv-20211128164148410800000004.s3.amazonaws.com/works/converted/projects/82116895-a386-8a33-f6e0-347408413e33/revisions/105ac24c-32d8-418a-87ee-778854f3d618/info.json

- アップロードされた画像を表示する方も、どこで止まっているのか見てみます。

2021-12-02 22:56 UTC, LumaKernel commented
いま一緒にやろうとしている S3 Key + Bucket を構築する関数と、S3 Key + Bucket + env から minio/s3 両対応の URL を作る関数を、それぞれ分けて考えると良いと思います。
最新のコミットではローカルで見えなくなってるとかではないですか。

2021-12-04 14:00 UTC, LumaKernel commented
おー。とりあえずプレビューは見えてる。

2021-12-04 14:02 UTC, maihrs55 commented
NODE_ENVでURLを分けるべきかなと思って修正しています。
反応できていなくてすみません。

2021-12-04 14:08 UTC, LumaKernel commented
NODE_ENV より S3_ENDPOINT かな。今のところ実質的に S3_ENDPOINT の有無が minio or s3 の判別に全体を通して使われている

2021-12-04 23:36 UTC, LumaKernel commented on pkg/web/src/utils/Scroller.tsx
> +export const scroller = (id: string) =>
`Scroller.tsx` というファイル名は違和感ありません？

2021-12-04 23:38 UTC, maihrs55 commented on pkg/web/src/utils/Scroller.tsx
> +export const scroller = (id: string) =>
確かにtsxではないです。修正します。

2021-12-04 23:41 UTC, LumaKernel commented on pkg/web/src/utils/Scroller.tsx
> +export const scroller = (id: string) =>
そちらよりは upper camel case のほうです。

2021-12-04 23:42 UTC, LumaKernel commented
/deploy

2021-12-04 23:43 UTC, LumaKernel approved these changes
https://github.com/violet-ts/violet/issues/146 リファクタリング issue はとりあえず分離しておいた。
dotenv も気になるけどこれも別でリファクタリングしようと思っている。

Looks cool. deploy して動作確認してあとは良さそう。

2021-12-04 23:45 UTC, LumaKernel commented on pkg/api/src/service/browser.ts
> +const endPoint = dotenv.S3_ENDPOINT
endpoint

end point でも正しそうですが、統一をお願いします。

2021-12-04 23:49 UTC, maihrs55 commented on pkg/web/src/utils/Scroller.tsx
> +export const scroller = (id: string) =>
すみません...。もっと気がつけるように注意します。修正しました。

2021-12-04 23:55 UTC, LumaKernel commented on pkg/web/src/utils/Scroller.tsx
> +export const scroller = (id: string) =>
いえ、すみません言葉足らずで…

2021-12-05 00:36 UTC, maihrs55 commented on pkg/api/src/service/browser.ts
> +const endPoint = dotenv.S3_ENDPOINT
endpointで統一します。
dotenvも使うならlibなどに入れたほうが良いということですね。

2021-12-05 00:38 UTC, maihrs55 commented
- #145 がmain にマージされたら、マージします。

2021-12-05 00:39 UTC, LumaKernel commented
A5サイズ1p (1024MB): 6.7s
A0サイズ1p (1024MB): 65s (そしてスペース足りず変換できない)
/tmp のスペースは 512MB
これは私のほうでどうにか対策を考えておきます…

2021-12-05 00:41 UTC, LumaKernel commented
CI の修正 merge しました、 rebase してみてください。

2021-12-05 15:05 UTC, maihrs55 commented
CI通りました。
マージしてもらっても良いでしょうか。

2021-12-05 15:16 UTC, solufa commented on pkg/web/src/utils/scroller.ts
> +  document.querySelector(`[data-search-id="${id}"]`)?.scrollIntoView()
data-search-idがスクロールのための属性値だという情報が散らばっている
なぜsearchなのかも気になる

2021-12-05 15:16 UTC, LumaKernel commented on pkg/api/src/service/browser.ts
> +const endPoint = dotenv.S3_ENDPOINT
ここ元に戻っちゃってそう

2021-12-05 15:20 UTC, LumaKernel commented on pkg/web/src/utils/scroller.ts
> +  document.querySelector(`[data-search-id="${id}"]`)?.scrollIntoView()
data-search-id 自体は探すためのIDということで search という語でサンプルを書きました。

2021-12-05 15:24 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/PaginationBar.tsx
> +export const PaginationBar = (props: { clickChevron: (chevronUp: boolean) => boolean }) => {
chevronはこのコンポーネント都合の表現に過ぎず、利用側から見てchevronに感心はないし、Bool値でUpDown言われても謎
デザインがchevronからarrowに変わったらProps名も変えるのか？

外部からみた関心は、「ユーザーが次を見たいのか、前を見たいのか」
props二つに分けるのが良い

2021-12-05 15:26 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +      <AlertModal open={open} onClose={(state: boolean) => unsupportedFileType(state)} />
unsupportedFileTypeをアロー関数で囲う意味がわからん

2021-12-05 15:26 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    return chevronUp
誰のためにchevronUpを返しているのか

2021-12-05 15:27 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    const index = arrRevisionId.findIndex((d) => d === id)
indexOf

2021-12-05 15:29 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    setOpen(state)
unsupportedFileTypeとsetOpenの違いはどこ

2021-12-05 15:34 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +        <MainContent key={revision.id} data-search-id={revision.id}>
複数refsでスクロール対象管理できないかな
https://qiita.com/tonio0720/items/c265b9b65db3bb76f2d3#%E8%A4%87%E6%95%B0refs

Violet全体で「data-search-id」が衝突しないように注意するのがコスト高い

2021-12-05 15:36 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/EmptyWork/index.tsx
> +          <AlertMessage>Unsupported File Format!</AlertMessage>
これAlertModalも似たような表現してないか？
AlertModalをmoleculesあたりに移して汎用化して使えばいいのでは

2021-12-05 15:38 UTC, solufa commented on pkg/lambda/conv2img/src/convert-object.ts
>            Key: `${convertedKeyPrefix}/${i}.${e}`,
ファイル名をlowerCamelCaseに変えておいてください

2021-12-05 15:39 UTC, solufa requested changes
修正お願いします

2021-12-05 15:52 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +        <MainContent key={revision.id} data-search-id={revision.id}>
それが良さそうですね。もともと話していたのでも、そもそもランダムにするつもりで言ったのでいずれにしても使う側が管理するものではないかな。

その記事はアンチパターン踏んでいそう、https://stackoverflow.com/questions/54633690/how-can-i-use-multiple-refs-for-an-array-of-elements-with-hooks も確認してみてください。

2021-12-05 23:26 UTC, maihrs55 commented on pkg/web/src/utils/scroller.ts
> +  document.querySelector(`[data-search-id="${id}"]`)?.scrollIntoView()
スクロールする時の目印なので、scroll-target-id に変更しました。
 
> 情報が散らばっている

id はどこかに集約すべきということでしょうか。

2021-12-05 23:32 UTC, LumaKernel commented on pkg/web/src/utils/scroller.ts
> +  document.querySelector(`[data-search-id="${id}"]`)?.scrollIntoView()
`scroll-target-id` という名前を定数化したいということです。

2021-12-06 13:16 UTC, solufa commented on pkg/web/src/utils/scroller.ts
> +  document.querySelector(`[data-search-id="${id}"]`)?.scrollIntoView()
複数refを使って
`refElems[targetIndex].scrollIntoView()`
みたいな感じにならんかな

2021-12-08 02:18 UTC, solufa commented on pkg/web/src/types/tools.ts
> +export type pageDirection = 'nextPage' | 'previousPage'
PageDirection

2021-12-08 02:19 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    const targetIndex =
targetRef

2021-12-08 02:24 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/EmptyWork/index.tsx
> +import { AlertModal } from '../Revision/AlertModal'
ファイルの場所が良くない気がする

2021-12-08 02:25 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
>  import { StreamBar } from '../components/StreamBar'
from './Revision'
from './StreamBar'

でも同じ？

2021-12-08 02:27 UTC, solufa requested changes
scrollIntoViewの処理は良くなってる

2021-12-08 15:19 UTC, solufa approved these changes
良い感じ、お疲れさん

2021-12-08 15:19 UTC, merged