PaginationバーでGridスクロール
violet-ts/violet pull request #151
Opened 2021-12-11 12:21 UTC by maihrs55

## Overview
- Resolves #148 
    - 一番上の階層の階層を overflow: hidden にする
    - 最上部・最下部までスクロールしたときに次のリビジョンに上下矢印ボタンで作成した
        ScrollIntoViewを使用してグリッドスクロールする
        - position: absolute + transition + top: -n * 100% としたときに、
            flexが崩れてしまうため

2021-12-11 12:22 UTC, maihrs55 commented
/preview/status

2021-12-13 06:57 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +  const onScroll = (element: React.UIEvent<HTMLDivElement>, index: number) => {
命名が似ていて初見でonScroll/onWheelの違いがわからん

2021-12-13 07:13 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
>    const clickPagenation = (pageDirection: PageDirection, index: number) => {
Pagenation -> Pagination

2021-12-13 12:02 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
> +    if (clientHeight > view) onScroll(element, index)
onScrollでclickPaginationしたあとに下でまたclickPaginationすることにならない？
仮にこれで上手く動いてるとしても、コードの読み手が混乱する

2021-12-13 12:04 UTC, solufa requested changes
リサイズするとずれるし、スクロールと矢印ボタンを組み合わせるとリビジョンの中間で止まったりするのでアプローチを変えた方がいいかも・・・？

2021-12-13 12:43 UTC, LumaKernel commented
/deploy

(基本 `/deploy`  叩いちゃってください)

2021-12-13 22:47 UTC, maihrs55 commented
スクロールの操作感もあまり良くなさそうなので、全体的に見直します。

2021-12-15 14:46 UTC, maihrs55 commented
/deploy

2021-12-15 15:19 UTC, maihrs55 commented
- scroll-snap でリビジョンごとに移動する方針にしました
    - overflow:scroll;にし、最上位のスクロールはWindowの外部に位置するようにしています

![image](https://user-images.githubusercontent.com/52160187/146213379-c061600e-a497-4e1c-b07c-e149922a497b.png)

2021-12-15 15:20 UTC, maihrs55 commented
/deploy

2021-12-16 03:41 UTC, solufa commented
再レビュー依頼が出てないけどこれはレビュー待ち状態？
あとデプロイに失敗してるっぽい

2021-12-16 16:19 UTC, maihrs55 commented
/deploy

2021-12-17 11:59 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/MainColumn.tsx
>    const clickPagenation = (pageDirection: PageDirection, index: number) => {
修正しました。

2021-12-17 12:05 UTC, maihrs55 commented
- Pagination Bar を右側に移動するのを以下のイシューで対応します。
    - #153

2021-12-17 12:24 UTC, solufa approved these changes
当初よりだいぶスッキリしていて良い

2021-12-17 12:24 UTC, merged