タブ並べ替え
violet-ts/violet pull request #166
Opened 2022-01-08 12:30 UTC by maihrs55

## Overview
- Resolved #160 
    - タブを並べ替える
    - 移動したタブがアクティブタブではない時に、アクティブにする

- タブをワークのスペースにドラッグするとDropperが反応するバグに別チケットで対応する
    ※ 本チケット対応前にも発生する
    - #165 
 
## Image
![move-tab](https://user-images.githubusercontent.com/52160187/148644193-acd1c660-11d5-44b3-9832-3788fd574f73.gif)

2022-01-08 12:32 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +import type { WorkId } from '@violet/lib/types/branded'
このファイルは格納場所を変更したファイルです。

2022-01-08 12:32 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +  const changeStyleOfHoverItem = (hoverItem: WorkId) => {
これ以降のメソッドを追加しました。

2022-01-08 12:33 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +                  <Draggable
Dragableのコンポーネント を追加しました。

2022-01-08 13:47 UTC, maihrs55 commented
/deploy

2022-01-09 03:32 UTC, maihrs55 commented
/preview/status

2022-01-09 04:23 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +                <>
このFragment不要にみえる

2022-01-09 04:27 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +  })
これは `props.operationData.tabs.length` が変化しても問題ない？
dependency listなしでuseDrop使って平気なのかわからん

2022-01-09 07:36 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/Dragable.tsx
> +  canDrag?: boolean
使われてない

2022-01-09 07:36 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/Dragable.tsx
> +  itemType: 'work'
後から文字列増える予定？

2022-01-09 07:38 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/Dragable.tsx
> +  })
ここもDependencyなくてよいのか？

2022-01-09 07:39 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +const ItemType = 'work' as const
as const なしで work固定になるはず

2022-01-09 07:42 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +      const swapTabs = props.operationData.tabs.filter((_, index) => index !== dragIndex)
どっちも名前が関数用の命令形になってる
受動態っぽく書けばオブジェクト・配列名になる

2022-01-09 07:44 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +    setHoverItem(hoverItem)
changeStyleOfHoverItemで囲わなくても直接setHoverItemを渡せるはず

2022-01-09 07:45 UTC, solufa requested changes
カスタムフックに関数を渡す場合、依存する値をメモ化してしまうので大抵Dependencyを渡す方法が用意されている

2022-01-09 08:02 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +                <>
不要なので削除しました。

2022-01-09 08:16 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +  })
デフォルト値として引数がオブジェクトの場合、
引数に含まれている配列がdependency listとして使用されるようです。
そのため、不具合なく動作するため気がつきませんでした。
この場合、明示した方がわかりやすいでしょうか。

2022-01-09 08:17 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/Dragable.tsx
> +  canDrag?: boolean
削除しました。

2022-01-09 08:19 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +const ItemType = 'work' as const
修正しました。

2022-01-09 08:21 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +      const swapTabs = props.operationData.tabs.filter((_, index) => index !== dragIndex)
受動態で修正しました。

2022-01-09 08:23 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +    setHoverItem(hoverItem)
渡せました。修正しました。

2022-01-09 08:48 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/Dragable.tsx
> +  itemType: 'work'
増える予定はないので、constantにしました。

2022-01-09 08:51 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +  })
レンダリング毎にhoverの関数を更新しているため、動作に問題はありませんでした。
パフォーマンスに問題が出ない限り、公式のサンプルと同じ方法で使用します。

2022-01-09 08:57 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/Dragable.tsx
> +  })
以下コメントと同じ理由で、Dependencyをセットしないこととしました。
https://github.com/violet-ts/violet/pull/166/files#r780733499

2022-01-09 09:37 UTC, solufa approved these changes
LGTM

2022-01-09 09:37 UTC, merged