タブのスクロール
violet-ts/violet pull request #167
Opened 2022-01-09 10:43 UTC by maihrs55

## OverView
- Resolved #156
- ファイル名は全て表示する（ファイル名の長さにタブの幅を合わせる）
- hover した時にスクロールバーを表示する

2022-01-09 11:12 UTC, maihrs55 commented
/deploy

2022-01-10 05:11 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +  width: 100vh;
幅の単位にvh使っているのは意図通り？

2022-01-10 05:16 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/WorkTab.tsx
> +  }
親に通知する目的ではない関数をPropsで受け取る理由がない
必要な値全部親からもらってtabToHrefを素直に使う

2022-01-10 05:23 UTC, solufa requested changes
![image](https://user-images.githubusercontent.com/9402912/148721366-475e67ef-a0f0-4f2d-b744-930acce8fce7.png)
・Dirタブの右に縦線がない
・タブの下に少し隙間
・タブ横幅合計がある値以下だとHoverしてもスクロール出ない
意図したデザインならいいけど

2022-01-11 15:08 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +  width: 100vh;
意図的ではないので、
widthを計算するソースに修正しました。

2022-01-11 15:14 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/WorkTab.tsx
> +  }
tabToHrefを使用するソースに修正しました。

2022-01-11 15:51 UTC, maihrs55 commented
意図していないため、修正しました。
・Dirタブの右に縦線がない
・タブの下に少し隙間

横幅がスクリーンの横幅を超えない限り、スクロールバーが表示されないという点は
意図しているので、そのままとしています。

2022-01-12 21:42 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/WorkTab.tsx
> +                  <TabItem active={operationData.activeTab?.id === t.id}>
このへんかな、`tabIndex=-1` ほしい

2022-01-12 21:45 UTC, LumaKernel commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/WorkTab.tsx
> +                  <TabItem active={operationData.activeTab?.id === t.id}>
もしくはシンプルに button 使うなど。

2022-01-14 15:46 UTC, LumaKernel commented
/ preview/start

2022-01-14 15:46 UTC, LumaKernel commented
/preview/start

2022-01-15 04:17 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/WorkTab.tsx
> +                  <TabItem active={operationData.activeTab?.id === t.id}>
Tabキーの動作に気が回っていませんでした。
TabItem は button を使用しました。×ボタンに tabIndex=-1 をあてました。

2022-01-19 11:30 UTC, solufa requested changes
Windowsだけかもしれんけど
- スクロールできる状況でスクロールバーが出ないことがある
- 右のタブの右端がスクロールされない（xボタンがでない）

以下の画像は両方が再現されたときのもの

![image](https://user-images.githubusercontent.com/9402912/150121380-37e88d83-789f-46d5-a30c-5f6fff1cd6be.png)

2022-01-19 11:32 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/LeftColumn.tsx
>      return () => window.removeEventListener('resize', resize, false)
ここでclearTimeoutもすべきかも、100ms後にsetしてしまう可能性がわずかにある

2022-01-19 11:33 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +      setDisplayedScrollBar(false)
setDisplayedScrollBarに直接条件入れれればよいのでは

2022-01-19 11:33 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +          key={props.operationData.tabs[0].id}
keyはいるのか

2022-01-19 13:11 UTC, maihrs55 commented
/deploy

2022-01-22 04:11 UTC, maihrs55 commented
/deploy

2022-01-22 04:22 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +          key={props.operationData.tabs[0].id}
Key いらないところでした。

2022-01-22 04:23 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Tab/TabBar.tsx
> +      setDisplayedScrollBar(false)
直接入れる形に修正しました。

2022-01-22 05:21 UTC, maihrs55 commented
> Windowsだけかもしれんけど
> 
> * スクロールできる状況でスクロールバーが出ないことがある
> * 右のタブの右端がスクロールされない（xボタンがでない）
> 

LeftColumn の width が300px を超えた時に、
右側の TollBarが画面外に飛び出し、右側のタブも右端が画面の外に出ていました。
修正中です。

2022-01-22 06:19 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/LeftColumn.tsx
>      return () => window.removeEventListener('resize', resize, false)
return の中で clearTimeout をする処理に修正しました。

2022-01-22 06:23 UTC, maihrs55 commented
/deploy

2022-01-22 07:01 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +    () => window.innerWidth - projectBarWidth - leftColumnWidth,
依存に含まれていない可変な値をuseMemoでは扱えない
画面の横幅が変わっても検知ができない
HTML/CSSだけで解決出来そうに見えるんだけどなあ

2022-01-24 23:25 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +    () => window.innerWidth - projectBarWidth - leftColumnWidth,
- position が absolute, relative になっている Dropper を書き直しました。
- index.page.tsx のMainColumn のwidth に min-width を設定することで解決できました。

2022-01-24 23:27 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +    () => window.innerWidth - projectBarWidth - leftColumnWidth,
- Resolved #165 
    - Dropper を書き直したことで解消されました。

2022-01-24 23:29 UTC, maihrs55 commented
/deploy

2022-01-30 06:18 UTC, maihrs55 commented
PDFのドロップの処理を修正したところ、以下のバグも解消されました。
- #173

2022-01-30 09:43 UTC, maihrs55 commented
@solufa 
修正を終えています。再レビューを宜しくお願い致します。

2022-01-30 09:48 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/Parts/FileDropper.tsx
> +import { colors } from '@violet/web/src/utils/constants'
EmptyWork と Revision 用のFileDropperを作成しました。

2022-01-30 09:50 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +  min-width: 0;
これの追加で、 TabBar の Width が画面外にはみ出さないようになりました。

2022-01-31 17:01 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +  const [leftColumnWidth, setLeftColumnWidth] = useState(300)
これここに書かなくてよくなったのでは？

2022-01-31 17:01 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +  min-width: 0;
これは知らなかった、良く見つけたね

2022-01-31 17:04 UTC, solufa requested changes
あともうちょい

2022-02-01 09:41 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/components/LeftColumn.tsx
> -    setDiffX(width - e.pageX)
width をもとに戻しました。

2022-02-01 09:42 UTC, maihrs55 commented on pkg/web/src/pages/browser/[[...paths]]/index.page.tsx
> +  const [leftColumnWidth, setLeftColumnWidth] = useState(300)
ここにある必要ありませんでした。もとに戻しました。

2022-02-01 09:43 UTC, maihrs55 commented
コンフリクト確認中です。

2022-02-01 13:27 UTC, maihrs55 commented
コンフリクトも修正しました。

2022-02-01 14:14 UTC, solufa approved these changes
いい感じに見える

2022-02-01 14:14 UTC, merged

2022-02-06 11:42 UTC, LumaKernel commented
/preview/force-destroy