chore: introduce notios for dev
violet-ts/violet pull request #184
Opened 2022-03-11 11:01 UTC by LumaKernel

![image](https://user-images.githubusercontent.com/29811106/157854694-2320ed4d-f00d-46dc-84bf-93fd98fa1331.png)
容量なさすぎて docker 立ち上げてないんですけど、良さそうです。

2022-03-11 15:39 UTC, LumaKernel commented
別のとこ原因で落ちていた。修正したら動いた。
![DA6CED00-E947-4977-B831-ED45222A6EA6](https://user-images.githubusercontent.com/29811106/157898800-3620109d-c7f9-4823-aec8-5c3b0b675598.png)
![F1D9B1B4-1B68-401B-A6A8-CD716759AE4A](https://user-images.githubusercontent.com/29811106/157899010-741eaed9-9622-4180-aec3-56b74a0a37d6.png)

ipad termiusでも動いた

2022-03-23 04:25 UTC, solufa requested changes
notios公表前だけど、ドッグフーディング用にマージしてみることにする
これは楽しみ

2022-03-23 04:26 UTC, solufa commented
Approveしたいのに間違えた・・・

2022-03-23 04:26 UTC, solufa approved these changes
LGTM

2022-03-23 04:26 UTC, merged