プロジェクト名変更の履歴管理機能
violet-ts/violet pull request #185
Opened 2022-03-16 14:31 UTC by shuheiest

古いプロジェクト名からアクセスがあった場合でも、新しいプロジェクト名のURLにアクセスを可能としました。
![動作確認](https://user-images.githubusercontent.com/88891567/158612291-7466bb18-42e9-4e3d-a8b2-75e69e7edc72.gif)

2022-03-17 13:35 UTC, shuheiest commented
/deploy

2022-03-17 13:44 UTC, shuheiest commented
preview/start

2022-03-23 04:18 UTC, solufa commented
開発時にはまってたポイントがfrourio側で対策されましたよ
https://github.com/frouriojs/frourio/issues/226

2022-03-23 04:22 UTC, solufa commented on pkg/web/src/pages/browser/[[...paths]]/usePage.ts
> +  }
このあたり、useAspidaSWR+useEffectで書き直してみて欲しいです

2022-03-23 04:23 UTC, solufa requested changes
SWRの習得頑張りましょうー

2022-03-29 11:35 UTC, shuheiest commented on pkg/web/src/pages/browser/[[...paths]]/usePage.ts
> +  }
修正してみたので、再レビューお願いいたします。

2022-04-13 14:21 UTC, solufa approved these changes
修正に気付かなかったすまぬ・・・
いいですね！

2022-04-13 14:21 UTC, merged