追加アップロード用ドロップUI
violet-ts/violet pull request #62
Opened 2021-10-31 11:34 UTC by maihrs55

### ファイル追加機能
- ワーク追加ボタンを作成
- すでにリビジョンがあるワークにファイルをドロップした場合、リビジョンを追加
- ワークが追加されたときに画面の高さを超えたらスクロールする（別タスクでリビジョンのスクロールと同期させる）

### 周辺機能の修正
- LeftColumnの幅を変更する時の「 MovableArea 」を最前面に表示

### 画面イメージ
![image](https://user-images.githubusercontent.com/52160187/139581053-0b80e288-82bd-474a-a953-91d8fed18a89.png)

2021-10-31 14:13 UTC, maihrs55 commented on pages/browser/[...pathes]/components/Revision/index.tsx
> +  min-height: 200px;
別タスクでワークスプレビューの表示を対応することを前提にして作成しています。

2021-11-02 14:39 UTC, solufa commented
Win/Chromeだとスクロールバー地獄
![image](https://user-images.githubusercontent.com/9402912/139868770-b436d660-0900-4bb6-a81e-88f4b6cf4466.png)

2021-11-02 14:40 UTC, solufa commented on pages/browser/[...pathes]/components/TabBar.tsx
> +  overflow: scroll;
scrollにするとスクロール不要でもWinで常時出てしまう

2021-11-02 14:42 UTC, solufa commented on pages/browser/[...pathes]/components/LeftColumnResizeAbleArea.tsx
> +}
分割するには小さすぎるような・・・
汎用化するならcomponentsディレクトリ

2021-11-02 14:47 UTC, solufa commented on pages/browser/[...pathes]/components/Revision/AddButton.tsx
> +  dropFile: (e: React.ChangeEvent<HTMLInputElement>) => void
eventオブジェクトごと親に渡すのは不親切
親側でDOMの初期化とか型のハンドリングが発生する
結局親が欲しいのはFile型のオブジェクトだけでは？

2021-11-02 14:48 UTC, solufa commented on pages/browser/[...pathes]/components/Revision/AddButton.tsx
> +  }
&要らないような気がする

2021-11-02 14:52 UTC, solufa commented on pages/browser/[...pathes]/components/StreamBar/index.tsx
> +  position: sticky;
stickyの一般用法から外れていて意図不明な感じ
Winだとここ3行なくても同じに見える

2021-11-02 14:53 UTC, solufa commented on pages/browser/[...pathes]/components/Revision/index.tsx
> +        </>
Fragmentいらない

2021-11-02 14:54 UTC, solufa commented on pages/browser/[...pathes]/components/Revision/index.tsx
> +          openedTabRevisions[0].revisions.map((_o, i) => (
openedTabRevisions?.[0].revi......

2021-11-02 15:07 UTC, solufa commented on pages/browser/[...pathes]/components/Revision/index.tsx
> +    if (!file) return
型見る限り必ずfileはあるはずだけどfalsyになるケースはある？

2021-11-02 15:08 UTC, solufa commented on pages/browser/[...pathes]/components/Revision/index.tsx
> +  overflow-y: scroll;
これもWinで常にスクロールバーが出てしまう

2021-11-02 15:09 UTC, solufa requested changes
ひとまずここまで修正

2021-11-03 05:21 UTC, maihrs55 commented on pages/browser/[...pathes]/components/LeftColumnResizeAbleArea.tsx
> +}
Portalは分割しないと使えないと勘違いしていました。
LeftColumn.tsxに吸収しました。

2021-11-03 09:14 UTC, solufa approved these changes
LGTM

2021-11-03 09:14 UTC, merged