Introduce Pnpm + Changes to deploy web
violet-ts/violet pull request #63
Opened 2021-11-01 06:59 UTC by LumaKernel

- [x] すべてのscriptの成功
  - [x] primsa migrate dev
  - [x] root `generate`
  - [x] root `typecheck`
  - [x] root `build`
    - [x] api `_:build`
    - [x] frontend `_:build`
  - [x] root `dev`
    - [x] api `_:dev`
    - [x] frontend `_:dev`
  - [x] root (only) `lint`
  - [x] root (only) `lint:fix`
  - [x] `test`
  - [x] `start`
- [x] esbuild のセットアップ
- [x] CI の成功
- [x] readme の修正
- [x] codeowners
- [x] docker compose
  - [x] up
  - [x] down して up

- [x] ビルドの成功
  - [x] api
    - [x] serve
  - [x] frontend
    - [x] serve

---

closes https://github.com/violet-ts/violet/issues/51

2021-11-02 10:06 UTC, LumaKernel commented
pnpm、ビルドサイズとビルド時間にも良い影響があるみたい

680MB→560MB
4.5m → 3m

Actions は実 build によるテストも加えてそんなに変わらない時間になっている。

2021-11-03 09:29 UTC, solufa requested changes
すみません、先行していたPRをマージした都合でコンフリクト出ています

2021-11-03 09:30 UTC, solufa commented
@maihrs55 が動作確認中
@LumaKernel 
他のメンバーのローカル作業がなくなったので動作確認出来たら今後のPRに優先してこれをマージします

2021-11-03 10:13 UTC, maihrs55 commented
移行方法の手順で動作確認できました。
server/ と util/ を手動で削除しました。

2021-11-03 10:33 UTC, LumaKernel commented
/help

2021-11-03 10:51 UTC, LumaKernel commented
- https://api-lumakernel-pr-5.violet-dev.com/
- https://web-lumakernel-pr-5.violet-dev.com/


一応 migration まではコメントでできるようになったのですが seed.ts が TS なので、 JS にトランスパイルするというのをやったあとに seed できるようになります。

2021-11-03 10:52 UTC, LumaKernel commented
他 PR のマージはもともとやるつもりだったのでやりますー。

2021-11-03 10:54 UTC, LumaKernel commented
/help

2021-11-03 15:46 UTC, LumaKernel commented
- [x] main をマージ
  - 各ファイルの差分無損失チェックリスト。特徴的な差分が反映されているかチェックしました。
  - https://github.com/violet-ts/violet/pull/67
    - 全ファイル
    - [x] pages/browser/[...pathes]/components/AddArea.tsx
    - [x] pages/browser/[...pathes]/components/Explorer/CellName.tsx
  - https://github.com/violet-ts/violet/pull/62
    - 全ファイル
    - [x] pages/browser/[...pathes]/components/EmptyWork/index.tsx
    - [x] pages/browser/[...pathes]/components/FileTypeAlertModal.tsx
      - [x] 改名元の削除
    - [x] pages/browser/[...pathes]/components/LeftColumn.tsx
    - [x] pages/browser/[...pathes]/components/ProjectBar.tsx
    - [x] pages/browser/[...pathes]/components/Revision/AddButton.tsx
    - [x] pages/browser/[...pathes]/components/Revision/index.tsx
    - [x] pages/browser/[...pathes]/components/StreamBar/index.tsx
    - [x] pages/browser/[...pathes]/components/TabBar.tsx
    - [x] pages/browser/[...pathes]/index.page.tsx
    - [x] server/utils/constants/index.ts
  - https://github.com/violet-ts/violet/pull/65
    - 一部はこちらでマージ後変更
    - [x] docker-compose.yml
    - [x] docker/lambda/Dockerfile
      - docker/lambda/conv2img/Docker へ移動、pnpm
    - [x] docker/lambda/envValues.ts
      - pkg/def/envValues.ts へ
    - [x] docker/lambda/index.ts
    - [x] docker/lambda/package.json
    - [x] docker/lambda/s3.ts
    - [x] docker/lambda/tsconfig.json
    - [x] server/api/browser/works/_workId@string/revisions/controller.ts
    - [x] server/utils/s3.ts
- [ ] 再度一連の流れを確認
- [ ] GitHub Actions

2021-11-04 02:42 UTC, solufa requested changes
docker/lambda/yarn.lock は不要なファイル？
pkg/lambda/conv2img/src/index.ts と pkg/lambda/conv2img/src/s3.ts のimport周りを見る限りlintコマンドが機能していないかも

2021-11-04 03:49 UTC, solufa approved these changes
LGTM

2021-11-04 03:50 UTC, merged

2021-11-04 08:59 UTC, LumaKernel commented
/help

2021-11-04 09:00 UTC, LumaKernel commented
動いた！