feat: add lambda for pdf convertion
violet-ts/violet pull request #65
Opened 2021-11-02 09:03 UTC by solufa

dockerにlambdaを追加しました

libreofficeでPDFに変換できるファイルなら何でも画像に変えてくれるはず

docker-compose up -d で新しいWorkにPDFをドロップすると以下画像のようにjpg/png/webp/jsonが生成される

jpg/pngはlambdaで生成してみてサイズが小さい方をS3に上げるようにした

![image](https://user-images.githubusercontent.com/9402912/139813822-e67a9517-b395-4d3c-b7f8-0c65392e8596.png)

@LumaKernel 
lambdaのDockerFileとdocker-composeの書き方を主に見てほしいです
イメージコンテナ使ってAWSにそのままlambdaをデプロイできるつもりで作りました

@maihrs55 
S3のrevisionsの末端ディレクトリ名をconverted/originalに変えたりしました
そっちのローカルでも問題なく動くか見てほしい

2021-11-02 09:05 UTC, solufa commented on .eslintignore
> +docker/lambda/*.js
ローカルでyarn buildするとtsからjsが生成されてしまうのでignore

2021-11-02 09:06 UTC, solufa commented on docker-compose.yml
> +      mc event add minio/$$S3_BUCKET arn:minio:sqs::1:webhook --event put"
このコマンドでminioにWebhookを登録したらStopするコンテナ

2021-11-02 09:07 UTC, solufa commented on docker/lambda/Dockerfile
> +RUN yum install ImageMagick libwebp-tools -y
ここと上の1行でレイヤーまとめていいのか種別で分けておく方がいいのかよくわかってない

2021-11-02 09:09 UTC, solufa commented on docker/lambda/envValues.ts
> +export { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_REGION, S3_ENDPOINT, S3_BUCKET }
これ以外のTSファイルもそうなんだけど、serverとスクリプト共有するのがだいぶ面倒な感じなので再定義している

server側でのみ必要なモジュールをlambdaにもinstallしなきゃいけなくなったりする

2021-11-02 09:16 UTC, solufa commented on docker/lambda/index.ts
> +
画像と一緒に生成されるinfo.json使ってフロントではこんな感じになるはず

```tsx
json.fallbackImageExts.map((ext, i) =>
  <picture>
    <source srcset={`${i}.webp`} type={CONTENT_TYPES.webp} />
    <source srcset={`${i}.${ext}`} type={CONTENT_TYPES[ext]} />
   <img src={`${i}.${ext}`} />
  </picture>
)
```

2021-11-02 09:17 UTC, solufa commented on docker/lambda/index.ts
> +  // Todo: mozjpeg
mozjpegはyumになくてソースからビルドする必要があるらしくて後回し

2021-11-02 09:18 UTC, solufa commented on server/api/browser/works/_workId@string/revisions/controller.ts
> +        filename: body.uploadFile.filename,
lambda側が拡張子でファイル種別を判断するのと、オリジナルファイルをDLしやすいようにfilenameで保存するように変えた

2021-11-02 09:25 UTC, LumaKernel requested changes

2021-11-02 09:25 UTC, LumaKernel commented on docker/lambda/s3.ts
> +import { fromContainerMetadata } from '@aws-sdk/credential-providers'
```suggestion
import { fromInstanceMetadata} from '@aws-sdk/credential-providers'
```

多分 `fromInstanceMetadata` だと思うのですが、一旦こっちに変えてもらって、後々調整して動かなければまた考えようかと思います。

2021-11-02 09:25 UTC, LumaKernel commented on docker/lambda/Dockerfile
> +
最後の yum 実行の後に `RUN yum clean all` をお願いします。

2021-11-02 09:25 UTC, LumaKernel commented on docker/lambda/Dockerfile
> +RUN npm install -g yarn
バージョン指定子つけてください。 `yarn@1` or `yarn@1.22.17`、明示的にバージョン挙げれる後者が嬉しいです

2021-11-02 09:25 UTC, LumaKernel commented on docker/lambda/Dockerfile
> +RUN yarn install
```suggestion
RUN yarn install && yarn cache clean
```

2021-11-02 09:25 UTC, LumaKernel commented on docker/lambda/s3.ts
> +import { fromContainerMetadata } from '@aws-sdk/credential-providers'
間に合ったらデプロイまで試しますが、間に合わなければ別 PR で調整作業します。

2021-11-02 09:27 UTC, LumaKernel commented on docker/lambda/envValues.ts
> +export { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_REGION, S3_ENDPOINT, S3_BUCKET }
これ pnpm 入れるのできれいに `@violet/shared` みたいなモジュール作って解決できるのでその時作業します

2021-11-02 09:27 UTC, LumaKernel commented on docker/lambda/envValues.ts
> +export { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_REGION, S3_ENDPOINT, S3_BUCKET }
詳しくは infrastructure の方覗いてみてください。すべての環境変数を型で疎通させてます。

2021-11-02 09:28 UTC, LumaKernel commented on docker/lambda/Dockerfile
> +RUN yum install ImageMagick libwebp-tools -y
作業中は別々にしますが、作業終わって必要なものわかったら、一つにまとめてます。
hadolint に従うようにしてます、基本。

2021-11-02 09:52 UTC, LumaKernel commented on docker/lambda/Dockerfile
> +RUN yum install ImageMagick libwebp-tools -y
それぞれの変更分が x1, x2, x3, x4 とあったとして、

- x1 + x2 + x3 + x4
- (x1) + (x1 + x2) + (x1 + x2 + x3) + (x1 + x2 + x3 + x4)

のどちらになるかという話で、上にしようという話だと思います。

2021-11-02 10:44 UTC, LumaKernel commented
yum の各種パッケージのバージョンも固定したいので調べてみます。

2021-11-02 12:51 UTC, maihrs55 commented
@solufa 
> @maihrs55 S3のrevisionsの末端ディレクトリ名をconverted/originalに変えたりしました そっちのローカルでも問題なく動くか見てほしい

- ドロップしたときにはconverted/originalが生成される挙動を確認できました。
- Explorerから選択したときにはoriginalのみが生成されていました。想定通りでしょうか。

2021-11-02 13:36 UTC, solufa commented on docker/lambda/Dockerfile
> +RUN yum install ImageMagick libwebp-tools -y
1行にまとめました

2021-11-02 13:36 UTC, solufa commented on docker/lambda/envValues.ts
> +export { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_REGION, S3_ENDPOINT, S3_BUCKET }
pkg配下でモノレポになってて共有出来ている感じかーこのパターン出来るとありがたい

2021-11-02 13:37 UTC, solufa commented on docker/lambda/s3.ts
> +import { fromContainerMetadata } from '@aws-sdk/credential-providers'
fromInstanceMetadataに変えておきました

2021-11-02 13:37 UTC, solufa commented on docker/lambda/Dockerfile
> +
追加しました

2021-11-02 13:37 UTC, solufa commented on docker/lambda/Dockerfile
> +RUN npm install -g yarn
yarn@1.22.17を指定しました

2021-11-02 13:37 UTC, solufa commented on docker/lambda/Dockerfile
> +RUN yarn install
追加済み

2021-11-02 13:40 UTC, solufa commented
@maihrs55 
Explorerからもconvertedが生成される想定です
私の手元だと両方のパターンで生成されるな・・・
https://github.com/violet-ts/violet/issues/66
チケット作っておいたので再現できたら対応します

2021-11-03 07:08 UTC, LumaKernel commented on docker/lambda/index.ts
> +import type { Handler } from 'aws-lambda'
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/s3.d.ts#L3

`S3Handler` にできますかね。ところで気づいたんですが、確か S3 のイベント発火させると `.Recrod[0].s3.object.key` だった気がします。互換性ないのかな…？

https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html

minio で本物のS3イベント使えなければ差異吸収させといてもらえると助かります。

2021-11-03 07:13 UTC, LumaKernel requested changes

2021-11-03 07:13 UTC, LumaKernel commented on docker/lambda/index.ts
> +  if (!(data instanceof IncomingMessage)) return { err: true }
エラーを throw するようにしてもらうことはできますか、そのほうがログ見るときに助かります。私が出しているPRではちゃんと設定をしていてスタックトレースも見れるので throw さえしてもらえれば内容は適当でもどうにかなります。

`throw new Error('getObject no data')`

2021-11-03 07:13 UTC, LumaKernel commented on docker/lambda/index.ts
> +  if (!(data instanceof IncomingMessage)) return { err: true }
もしくは `getObject` 側で throw してください。

2021-11-03 09:16 UTC, solufa commented on docker/lambda/index.ts
> +import type { Handler } from 'aws-lambda'
minio対応してました、修正済み

2021-11-03 09:16 UTC, solufa commented on docker/lambda/index.ts
> +  if (!(data instanceof IncomingMessage)) return { err: true }
getObject でthrowしました

2021-11-03 10:56 UTC, LumaKernel approved these changes
以下を私の今後の確認事項として、一旦 approve します。

- [ ] 各 yum パッケージのバージョン確認
- [ ] Lambda のローカル動作確認
- [ ] Lambda のビルドと本物での動作確認

2021-11-03 11:04 UTC, solufa commented
@LumaKernel 
レビューどうもです
これは #63 の前後どちらでマージするのがいいですか？

2021-11-03 11:11 UTC, LumaKernel commented
先でどうでしょう。私は問題ありません。

2021-11-03 11:37 UTC, merged

2021-11-04 11:57 UTC, LumaKernel commented on docker/lambda/s3.ts
> +import { fromContainerMetadata } from '@aws-sdk/credential-providers'
後でやりますが、 `fromEnv()` が正解でした…
https://github.com/violet-ts/violet-infrastructure/issues/4