続けてフォルダが追加できなかった処理を修正
violet-ts/violet pull request #77
Opened 2021-11-04 12:52 UTC by shuheiest

updateApiWholeData(
    'desksList',
    apiWholeData.desksList.map((d) => (d.projectId === deskRes.projectId ? deskRes : d))
  )
調査を行ったところ上記処理で追加するworkが入る前のデータが返ってきていることが分かり、 useCallbackを使うことにより処理が正しくいくようになった。

2021-11-04 13:03 UTC, shuheiest commented
[#77 ](url)←の対応のプルリクになります。

2021-11-04 13:10 UTC, solufa commented
根本的な解決ではないので私が引継ぎする予定

2021-11-05 14:04 UTC, shuheiest commented
#69 を解決したところ #77 が修正されました

2021-11-05 14:12 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/Explorer/CellName.tsx
> +  const [editType, setEditType] = useState<'file' | 'folder'>('file')
よく考えたら命令形なので関数名に見える
editingTypeなら名詞

2021-11-05 14:13 UTC, solufa requested changes
変数名だけ変えてくれたらOK

2021-11-05 18:56 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/Explorer/CellName.tsx
> +  const [editType, setEditType] = useState<'file' | 'folder'>('file')
dd31488e84a32d46a45d5b76ec7fe6d933ab5e2a 修正しました。

2021-11-06 01:06 UTC, solufa approved these changes
LGTM

2021-11-06 01:06 UTC, merged