Work-Reivisionを1-N表示UI
violet-ts/violet pull request #86
Opened 2021-11-07 07:40 UTC by maihrs55

- Index page .tsxでMainColumnのPropsを細分化
- MainColumnのコンポーネント を作成
- Workの末尾のRevisionを取得する→ ワークの全てのリビジョンを取得する 処理変更
- StreamBarのスクロールが末尾まで行ったときに次のリビジョンにスクロールする

## 未対応
- ワークの上でのスクロール制御
- メッセージを更新したときにStreamBarに表示されない

2021-11-07 07:42 UTC, maihrs55 commented
help

2021-11-07 07:55 UTC, maihrs55 commented
/help

2021-11-07 07:56 UTC, maihrs55 commented
/build/api
/build/web
/build/lambda/conv2img

2021-11-07 07:57 UTC, maihrs55 commented
/preview/start

2021-11-07 09:09 UTC, maihrs55 commented
/preview/start

2021-11-07 09:19 UTC, maihrs55 commented
/preview/start

2021-11-07 09:24 UTC, LumaKernel commented
/preview/start

2021-11-07 09:27 UTC, LumaKernel commented
多分bot側バグです、直しときます

2021-11-07 09:29 UTC, LumaKernel commented
/preview/start

2021-11-07 09:56 UTC, LumaKernel commented
別 PR で先に dockerfile 修正しないとあかんですね…

2021-11-07 10:32 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/EmptyWork/index.tsx
> +      types.includes(targetFileType) ? sendFormData(e.target.files) : setOpenAlert(true)
2行にせずに
fileTypes.someを使う

2021-11-07 10:59 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/Revision/index.tsx
> +  const [openedTabRevisions, setOpenTabRevision] = useState(props.revision)
複数形でいい？props.revisionをuseStateに詰めなおす必要はありそう？

2021-11-07 10:59 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/MessageCell.tsx
> +      {props.message.replys && props.message.replys.length > 0 && (
replys?.length

2021-11-07 11:00 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/MessageCell.tsx
> +      {props.message.replys && props.message.replys.length > 0 && (
このmessageの型はApiMessageのままでOK？

2021-11-07 11:03 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +      apiWholeData.messagesList.some((r) => r.revisionId === messageRes.revisionId)
このsomeはtrue/falseのどちらかしか取らないわけではない？

2021-11-07 11:05 UTC, solufa requested changes
とりあえずここまで

2021-11-10 15:54 UTC, solufa commented
なんでこれCI回らないんだろう、謎

2021-11-11 00:48 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/MessageCell.tsx
>          </div>
divじゃなくfragmentで良さそうな気がした

2021-11-11 01:19 UTC, solufa requested changes

2021-11-11 01:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  let emptyRevisions: BrowserRevision[]
emptyRevisionsは意味があるのか？

2021-11-11 01:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +      messages: getMessagesByRevisionId(p.id),
型の絞り込みができずgetMessagesByRevisionIdが無駄に複雑になってる
ここで作り切ればいい

2021-11-11 01:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  const browserRevisionData = useMemo(() => {
useMemo((): BrowserRevision[] | void => {
にすればmapに型指定したりemptyRevisionsいらなくなる

2021-11-11 01:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +            <>
projectApiData.revisions?.length ? (
ではなく
browserRevisionData ? (

2021-11-11 01:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/usePage.ts
> +      revisions?.find((revision) => revision.id === m.revisionId)
some

2021-11-11 01:19 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +    const revisions = revisionsData.revisions.flatMap((revision) => revision.id)
ここ以降をupdateMessages関数にまとめる

2021-11-12 13:36 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  let emptyRevisions: BrowserRevision[]
意味ありませんでしたので、空の配列を返す処理に変更しました。

2021-11-12 13:37 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  const browserRevisionData = useMemo(() => {
useMemoの使い方、覚えます。ありがとうございます。

2021-11-13 02:32 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +    const revisionsData = revisionsRes.data
このuseEffectを上と分割したい理由はなんですか

2021-11-13 02:33 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +    })
こっちもawait

2021-11-13 02:34 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +    if (!projectApiData?.messages) return
if まとめる

2021-11-13 02:37 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +    }))
mapの型引数にBrowserRevisionを渡すとオブジェクト作成中に推論が効いて変数宣言せずにreturnできる

2021-11-13 02:38 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +        : [],
projectApiData.messages?.filter() ?? []

2021-11-13 02:39 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  overflow-y: scroll;
windowsで常時スクロールバーが出てしまうが意図的？

2021-11-13 02:40 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +            props.revision &&
props.revisionがない場合があるのか？

2021-11-13 02:41 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +            props.revision.messages.length > 0 && (
上でmapしているのにprops.revision.messages.lengthがゼロだったときにここは通過するのか？

2021-11-13 02:42 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +  }, [props.revision.messages?.length])
props.revision.messagesがない場合があるのか？

2021-11-13 02:44 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
>    const [content, setMessage] = useState('')
content/messageで名前が一致してない

2021-11-13 02:46 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/ReplyInputForm.tsx
> +  border: none;
divに不可視の背景色とボーダーを指定する意味があるのか？

2021-11-13 02:47 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/MessageCell.tsx
> +      {props.message.replys && props.message.replys.length > 0 && (
props.message.replysがない場合があるのか？

2021-11-13 02:49 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/MainColumn.tsx
> +  overflow-y: scroll;
これもwindowsで常時スクロールが出るからoverflow: autoで良い

2021-11-13 02:49 UTC, solufa commented on pkg/web/src/components/atoms/PencileIcon.tsx
> +export const PencileIcon = styled.button`
pencil

2021-11-13 02:57 UTC, solufa commented
思い通りに動いたあとに最適化作業を行っていないように見える
無駄な記述はないか、分岐可能性を削減できないかを頻繁に確認してください

2021-11-13 04:19 UTC, LumaKernel requested changes

2021-11-13 04:19 UTC, LumaKernel commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  const browserRevisionData = useMemo((): BrowserRevision[] | void => {
`void` の実態は `undefined` ですが、値として使わない時に使うので基本 `void` 単体で使い、値として使う場合は `| undefined` か `| null` として `return undefiend` か `return null` としてください
明示的に nullish を返すときには `null` を私はよく使う気がします

`void` は、このケースは関係ありませんが一般的にはどんな値でもおかしくないので使ってはいけない、ということになります。 `const f: () => void = () => 0` はエラーが出ません

https://www.typescriptlang.org/docs/handbook/2/functions.html

> void represents the return value of functions which don’t return a value.

2021-11-13 04:25 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +    const revisionsData = revisionsRes.data
updateMessage にした後に、まとめられていませんでした。

2021-11-13 05:00 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +        .flatMap((revision) => revision.id)
flatなくても、問題なかったです。

2021-11-13 05:07 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  overflow-y: scroll;
意図的ではないです。

2021-11-13 05:10 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/ReplyInputForm.tsx
> +  border: none;
buttonにしていた名残でした。

2021-11-13 05:29 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +            props.revision.messages.length > 0 && (
分岐の必要はなかったです。

2021-11-13 05:44 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +  const browserRevisionData = useMemo((): BrowserRevision[] | void => {
void,undefind,null だと、
そのあとの分岐（browserRevisionData ? ）でうまく画面表示ができないことが判明したので、
空の配列を使いました。
返り値でany,voidになると、扱い方がわかっていなかったのでリンク先、見てみます。

2021-11-13 07:25 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/MessageCell.tsx
> +      {props.message.replys && props.message.replys.length > 0 && (
props.message.replysって常に配列型ではないのか？

2021-11-13 07:25 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/ReplyInputForm.tsx
> +  border: none;
消さないの？

2021-11-13 07:27 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +  }, [props.revision.messages?.length])
props.revision.messagesは常に配列じゃないの？

2021-11-13 07:29 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +          .map((r) =>
2回mapしない

2021-11-13 07:30 UTC, solufa requested changes
既存のコメント分が修正されてないので再度全部確認してください

2021-11-13 08:21 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +  }, [props.revision.messages?.length])
常に配列なので、分岐を削除しました。

2021-11-13 08:22 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +            props.revision &&
ない場合はありませんので、分岐を削除しました。

2021-11-13 08:26 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +            <>
Voidが返却される場合、browserRevisionData？を条件とするとEmptyWorkが表示されなくなるため、
空の配列を返却し、browserRevisionData.length > 0 を条件としました。

2021-11-13 08:37 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/ReplyInputForm.tsx
> +`
MessageIconをatomに追加して、ClickableAreaをContainerにしました。

2021-11-13 08:41 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +          .map((r) =>
mapを1回にまとめました。

2021-11-13 08:43 UTC, maihrs55 commented on pkg/web/src/components/atoms/PencileIcon.tsx
> +export const PencileIcon = styled.button`
全て「pencil」に修正しました。

2021-11-13 08:46 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/MessageIcon.tsx
> +    </Container>
PencilIcon .tsxとして、atomに追加しました。

2021-11-13 09:24 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +      apiWholeData.messagesList.some((r) => r.revisionId === messageRes.revisionId)
分岐をなくして、submitMessage の中に書きました。

2021-11-13 09:25 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
>    const [content, setMessage] = useState('')
contentに統一しました。

2021-11-13 09:26 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +                <MessageCell message={m} replyMessage={replyMessage} />
MessageCellにKeyを指定しました。

2021-11-13 09:28 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/index.tsx
> +        <ClickableArea onClick={() => submitMessage(props.revision.id)}>
親からのPropsを直接取得する処理に修正しました。

2021-11-13 09:29 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +    const revisions = revisionsData.revisions.flatMap((revision) => revision.id)
update Messages関数にまとめました。
初期表示の更新がうまくいかないので別のタスクで対応します。（ #87  ）

2021-11-13 09:31 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> +    })
message を上のawait の返り値とし、updateApiWholeDataの引数として使用する処理に修正しました。

2021-11-13 09:32 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +    if (!projectApiData?.messages) return
後者のifが機能していなかったため、前者のみを残しました。
後者の方はこの後のコメントで修正しています。

2021-11-13 09:34 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/StreamBar/ReplyInputForm.tsx
> +  border: none;
数カ所あり、削除できていませんでした。申し訳ありません。
全て削除しました。

2021-11-13 09:36 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/components/MainColumn.tsx
> +  overflow-y: scroll;
このタスクで対応したスクロールについて、全てautoに修正しました。

2021-11-13 09:36 UTC, maihrs55 commented on pkg/web/src/components/atoms/PencileIcon.tsx
> +export const PencileIcon = styled.button`
Pencileになっている箇所を全て修正しました。

2021-11-13 09:39 UTC, maihrs55 commented
@solufa 
修正漏れており、申し訳ありませんでした。
再度確認しました。
メッセージの更新の処理はもう少し修正が必要なため、
別のタスクで進めます。（ #87  ）

2021-11-13 09:43 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +      messages: getMessagesByRevisionId(p.id),
以下のレビューの処理に修正しています。
https://github.com/violet-ts/violet/pull/86#discussion_r748670831

2021-11-13 09:48 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +      id: p.id,
useMemo(() => projectApiData?.revisions.map<Br>(p => ({})) ?? [],

2021-11-13 10:05 UTC, maihrs55 commented on pkg/web/src/pages/browser/[...pathes]/index.page.tsx
> +      id: p.id,
空の配列を返すなら、即時返却する形に書き直せるということですね。
修正しました。

2021-11-13 10:11 UTC, solufa approved these changes
LGTM

2021-11-13 10:11 UTC, merged