プロジェクト追加API実装
violet-ts/violet pull request #93
Opened 2021-11-08 16:36 UTC by shuheiest

### 内容

- プロジェクトを追加するためのAPIの実装
- API使用して画面からプロジェクトの追加する処理を実装

### 動作
![動作確認](https://user-images.githubusercontent.com/88891567/140781366-3ab30b38-6d11-47c9-a28a-60f10b6dbd02.gif)

2021-11-08 16:45 UTC, shuheiest commented
/help

2021-11-08 16:46 UTC, shuheiest commented
build/api
build/web
build/lambda/conv2img
build/lambda/apiexec

2021-11-09 03:37 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +        selectedFullPath: d.id,
すでにあるProjectの状態が全部初期化されそう
開いていたタブとかなくなってしまう

2021-11-09 03:40 UTC, solufa requested changes

2021-11-09 03:40 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +    replace(newProject.body.id)
URLを上書きするより追加の方が良い気がする

2021-11-09 17:48 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +    replace(newProject.body.id)
urlは履歴が配列になっている
replaceは置換、Pushが追加

2021-11-09 17:50 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +        selectedFullPath: d.id,
初期値はidでもいいけど既存の情報をidで上書きすると選択状態が変わってしまわないか？

2021-11-10 14:25 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +    replace(newProject.body.id)
確認ありがとうございます。
修正しました。

2021-11-10 14:26 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +        selectedFullPath: d.id,
上書きしてしまっていたので、以下で修正しました。
`selectedFullPath: d.selectedFullPath`

2021-11-10 15:18 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +      }))
dのプロパティそのまま使うならmapする理由がわからん・・・

2021-11-10 15:18 UTC, solufa requested changes

2021-11-10 15:18 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> -
この改行は意図的に消した？たまたまコミットに含まれた？

2021-11-10 16:26 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +      }))
ご指摘の通りmapする意味ありませんでした。。
修正しました。

2021-11-10 16:28 UTC, shuheiest commented on pkg/web/src/pages/browser/[...pathes]/useFetch.ts
> -
コンソールログで値を確認した際に消してしまいコミットに含まれていたようです。
同じページ内のuseEffectではif文の後に改行していたので、元に戻しました。

2021-11-11 00:32 UTC, solufa commented on pkg/web/src/pages/browser/[...pathes]/components/ProjectNameInput.tsx
> +    createProject(label)
labelがあるなら作成完了するまでloadingしてほしい

2021-11-11 13:55 UTC, solufa approved these changes
LGTM

2021-11-11 13:55 UTC, merged